server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rmfrDB?serverTimezone=Asia/Seoul
    username: rmfr
    password: rmfr1234@
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: devsixt60@gmail.com
    password: nrajaumnhfmgkyqj
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000
logging:
  level:
    org:
      springframework:
        security: DEBUG